version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      app_network:
        ipv4_address: 192.168.1.100

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: 192.168.1.101

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
